### ISSUE TITLE
dashboard not functional

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#15]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1398

**Comment by xmonader** [comment]
can be closed now right?

**Comment by coesensbert** [comment]
yes, tested new dashboard with 2.3.0-alpha2 and working fine!

https://github.com/threefoldtech/tfgrid-sdk-ts/pkgs/container/playground/156448108?tag=2.3.0-alpha2
