### ISSUE TITLE
package the hub

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_deployment#23]
should be able to run it separately, with optional tooling to sync from another backend (can be as easy as rsync or so)

**Comment by coesensbert** [comment]
Need docker image and required flags

We got snapshots for tfchain and graphql, could do the same for the hub although it's a lot bigger dataset.
https://github.com/threefoldtech/grid_deployment/tree/development/grid-snapshots

**Comment by maxux** [comment]
Replication can be made via zdb directly and copying flist can be made via the API, it's possible to do a full replication with only public tools. I'll show some example.

**Comment by coesensbert** [comment]
https://github.com/threefoldtech/0-hub/pkgs/container/0-hub

https://github.com/threefoldtech/0-db/pkgs/container/0-db

Thx @maxux , will test it soon

**Comment by coesensbert** [comment]
see https://github.com/threefoldtech/tf_operations/issues/2113
