### ISSUE TITLE
Explorer Deployment

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_deployment#51]
# Todo

- Develop procedures to
   - deploy Explorer (has all stats)
   - each validator needs to have all data

# Related issue

- [See tfgrid validator stack main project issue for overview](https://github.com/threefoldtech/grid_deployment/issues/47)

**Comment by coesensbert** [comment]
What is needed here?
- by explorer you mean the dashboard?
- we need a compose to only deploy the dashboard? (as oppose to the whole backend stack)
- if we are talking about the full grid stack, which includes the dashboard that is already done

**Comment by mik-tf** [comment]
Yes I think you are right, we have this with the full grid stack. If I get other info I'll let you know but otherwise it's OK.

**Comment by mik-tf** [comment]
I will close this issue. I confirm we have the necessary "explorer" info with the current tfgrid full stack.
