### ISSUE TITLE
Set 3 independent grid stacks

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_deployment#60]
# Situation

We want to simplify the grid stack project for the first phase. We will not focus on having grid guardians from the community for now. We want to have redundancy and resiliency in a simple manner for now.

# Specs

We want to have:

- 3 independently running full tfgrid stack, running 3 times the same grid stack
- running on bare metal (ubuntu), not running on ZOS
- using docker compose, not flists nor dashboard apps
- set up in a way that it doesn't crash and is reliable
- 3 different names + DNS for each stack
- with a load balancer

# Updates

When we need to update the grid to new releases, we can have 1 of the 3 stacks that is updated and we can then test it and see if everything is OK before the other 2 can update with the new release.

# Future

Once we have this set up properly, we can think about going commercial or setting up the grid guardian project.

So for now we want to keep it simple and have redundant grid stacks running independently.

# Full Grid Stack

- Grid stack for each network (done): https://github.com/threefoldtech/grid_deployment/tree/development/docker-compose
- Hub (WIP): https://github.com/threefoldtech/grid_deployment/issues/49
- Boot Generator (WIP): https://github.com/threefoldtech/grid_deployment/issues/50
- Validator code (WIP): https://github.com/threefoldtech/grid_deployment/issues/52

# References

WIP being done by @coesensbert and @maxux

**Comment by mik-tf** [comment]
# Status

@coesensbert has set many mainnet grid stacks. 

See info_grid issue for links to stacks: https://github.com/threefoldtech/info_grid/issues/625

**Comment by coesensbert** [comment]
current list of mainnet backend stacks

- https://dashboard.grid.tf (DE)
- https://dashboard.be.grid.tf
- https://dashboard.fin.grid.tf
- https://dashboard.sg.grid.tf
- https://dashboard.us.grid.tf

docs: https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/grid_operations/grid_backend/mainnet
no loadbalancer / geo forwarder yet, will update that ticket

**Comment by coesensbert** [comment]
all specs satisfied, except the load balancer see: https://github.com/threefoldtech/grid_deployment/issues/56#issuecomment-2312085979
5 independent grid backend stacks deployed

infra docs: https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/grid_operations/grid_backend/mainnet
all links: https://github.com/threefoldtech/tf_operations/blob/master/docs/all-grid-v3-links.md
ops ticket: https://github.com/threefoldtech/tf_operations/issues/2649
