### ISSUE TITLE
[tfchain val] create snapshot compose stack

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#72]
https://github.com/threefoldtech/tfchain/issues/981

To lower storage requirements for tfchain validators we added new pruning flags. However this requires separate snapshot creation since pruning here is different from public RPC nodes.

- [x] devnet
- [x] qanet
- [x] testnet
- [x] mainnet

**Comment by sameh-farouk** [comment]
@sabrinasadik @coesensbert I suggest running these snapshots on one of the boot nodes for each network to avoid the cost of renting or dedicating new servers. Boot nodes typically use the same pruning flags as the validators and are primarily focused on syncing with the libp2p network with minimal additional work. Leveraging these servers for more tasks would be both practical and cost-effective.

**Comment by coesensbert** [comment]
Thanks @sameh-farouk for the suggestion, we will look into it

**Comment by coesensbert** [comment]
wip: testing

**Comment by coesensbert** [comment]
qanet: https://github.com/threefoldtech/grid_deployment/commit/a835c407c35227f2322aab1301305c975d8948cb
testnet: https://github.com/threefoldtech/grid_deployment/commit/96d8ed19429b3aa5bf028d0fa294ca25bb4f066b

all required deployment files created. qa and testnet still need to be setup and tested: https://github.com/threefoldtech/tf_operations/issues/2746

**Comment by coesensbert** [comment]
still need to finish the docs here

**Comment by coesensbert** [comment]
docs: https://github.com/threefoldtech/grid_deployment/tree/development/tfchain-validator-snapshots

done
