### ISSUE TITLE
TF Hub Tests by QA/Dev Team

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_deployment#78]
# Situation

- The TFHub procedure is most done but we'd need the QA/Dev team to test it further
- @coesensbert tested it to some extent.
  - Bert please add info here if possible/needed. 

# TODO

- Test the TFHub 

@xmonader or @sabrinasadik  can you check on your end who could test the TFHub? Thanks!

# Related Issue

- https://github.com/threefoldtech/tf_operations/issues/2754
  - environment to test grid stack

**Comment by mik-tf** [comment]
@A-Harby @hossnys

In relation with [issue #2754](https://github.com/threefoldtech/tf_operations/issues/2754), can you provide an update of the Hub testing? Lmk if you need anything to move this forward. Thanks!

**Comment by hossnys** [comment]
@A-Harby is still testing the tfchain backend part , and still facing some issues there , so please Ahmed put your update here once you reach the hub setup section in testing.

**Comment by A-Harby** [comment]
> @A-Harby @hossnys
> 
> In relation with [issue #2754](https://github.com/threefoldtech/tf_operations/issues/2754), can you provide an update of the Hub testing? Lmk if you need anything to move this forward. Thanks!

I'm just lost in the naming, but the TF Hub should be what?

**Comment by coesensbert** [comment]
The Hub is what serves the flists and it's data for the grid: https://hub.grid.tf/
It can be deployed with this: https://github.com/threefoldtech/grid_deployment/tree/development/grid-hub
The hub is one part of the guardian stack. It works as it is now, we need to find out someone else can also set it up. We have this code running here for example: https://hub.de.grid.tf/ / https://bootstrap.de.grid.tf/

**Comment by A-Harby** [comment]
I keep getting this error when trying to run the script.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nacl'
```
![image](https://github.com/user-attachments/assets/4aa7a7e0-3381-499b-9214-dec13e46df9d)

**Comment by coesensbert** [comment]
seems to go wrong here https://github.com/threefoldtech/grid_deployment/blob/development/grid-hub/install-hub.sh#L31
because of the flag `--break-system-packages`, @maxux prolly different python version? Can we safely remove this flag?

script does not seem to stop at this error, so it then complains about the missing `nacl` python module

**Comment by mik-tf** [comment]
@maxux any idea on this? 

Let's see if we can get this tests done. Thanks!

**Comment by maxux** [comment]
Which version of Ubuntu are you running ?
You can give a try to: `apt-get install python3-nacl python3-redis`
And comment the two `pip` line on the script.

**Comment by A-Harby** [comment]
> Which version of Ubuntu are you running ?

`Ubuntu 22.04.5 LTS`

**Comment by A-Harby** [comment]
It worked fine, and Docker ran with no issue.
![image](https://github.com/user-attachments/assets/cb98c844-014b-4e92-918b-bdbcc0c74db4)

And the sites were reachable.
![image](https://github.com/user-attachments/assets/1190e725-c240-4d51-be25-2c9f0118a08f)
![image](https://github.com/user-attachments/assets/bdab0116-c148-43c1-b2fe-feb7994ff6f2)

**Comment by A-Harby** [comment]
I created a PR for the fix too: https://github.com/threefoldtech/grid_deployment/pull/95

**Comment by mik-tf** [comment]
Well done @A-Harby thanks for this and thanks @maxux for the fix proposition. I think @coesensbert should be able to check the PR this week and merge it.

**Comment by coesensbert** [comment]
done, thanks!

**Comment by mik-tf** [comment]
Thanks Bert. I merged the PR.

@A-Harby do QA/Dev teams have anything else to test or we can close this issue?

Thanks.

**Comment by A-Harby** [comment]
> Thanks Bert. I merged the PR.
> 
> 
> 
> @A-Harby do QA/Dev teams have anything else to test or we can close this issue?
> 
> 
> 
> Thanks.

It's done for us now
