### ISSUE TITLE
Different versions in env file than the one used on the mainnet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_deployment#79]
Faced an issue with deploying the stack with that error. 
 
`2024-10-13T14:15:17.885Z INFO  [rmb_relay] redis pool size: 550
2024-10-13T14:15:17.885Z INFO  [rmb_relay] switch workers: 500
2024-10-13T14:15:17.885Z INFO  [rmb_relay] federation workers: 100
2024-10-13T14:15:17.885Z INFO  [rmb_relay] max number of users: 500000
2024-10-13T14:15:17.895Z ERROR [rmb::twin::substrate] failed to create substrate client with url "ws://tfchain-public-node:9944": Invalid Metadata: Invalid version
2024-10-13T14:15:17.907Z ERROR [rmb::twin::substrate] failed to create substrate client with url "ws://tfchain-public-node:9944": Invalid Metadata: Invalid version
cannot create substrate twin db object: failed to connect to substrate using the provided urls`

The version in the .env [file](https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/.env) are different than the one used in the [mainnet](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.grid.tf%2Fws#/explorer) now.
![image](https://github.com/user-attachments/assets/c0fd82c7-6133-4574-9a8b-480d5284e682)

**Comment by mik-tf** [comment]
@coesensbert

**Comment by coesensbert** [comment]
https://telemetry.tfchain.grid.tf/

In the telemetry one can see we have several tfchain versions running. 2.7.0 was the last mandatory upgrade, others after it where not marked mandatory for public rpc nodes.
We have about 7 stacks running in production with the [mentioned env file ](https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/.env) where we do not see this error.
As it would indeed be better to have same versions running everywhere, it's a work in progress. So I have doubts if the mentioned error is triggered by a faulty tfchain version. Could you provide access to that instance for me to investigate?

**Comment by A-Harby** [comment]
> https://telemetry.tfchain.grid.tf/
> 
> In the telemetry one can see we have several tfchain versions running. 2.7.0 was the last mandatory upgrade, others after it where not marked mandatory for public rpc nodes. We have about 7 stacks running in production with the [mentioned env file ](https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/.env) where we do not see this error. As it would indeed be better to have same versions running everywhere, it's a work in progress. So I have doubts if the mentioned error is triggered by a faulty tfchain version. Could you provide access to that instance for me to investigate?


Sure, I will.

**Comment by coesensbert** [comment]
issue was related to a btrfs setup mounted /var/lib , which should have been /srv for the current scripts to work.
since /var/lib was overwritten, best to redeploy the whole vm, mount btrfs setup at /srv and use the pre-req script to get going

resolved
