### ISSUE TITLE
Add Info On Keys Management for Validators

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_deployment#80]
# Situation

As @coesensbert highlighted, "Maybe we should add a bit more clarity in the docs which keys they have to keep, because they not need every key they create to set it up but for safety they need to keep them. Which is probably confusing currently".

# TODO

- Add info on keys management for validators

**Comment by coesensbert** [comment]
done: https://github.com/threefoldtech/grid_deployment/commit/c72127b81b20c177a7d695a581dbd7c4ef9f381e
