### ISSUE TITLE
Update installing stack script with retry

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_deployment#91]
The only way for the script to work for me was to do the download manually, which was a painful process with many tries. I think if we add a sample condition to make sure that download went successfully and if not to re-download it again, it would enhance the process a lot.

Also, I notice all of the previous updates done to the script were only to the mainnet script, so the other 3 network scripts will need the same update done, including this one too.

**Comment by coesensbert** [comment]
sure, do you have some Bash code suggestions? I have no idea how to make sure the file is downloaded, since the size of the snapshots changes daily. When I deployed the stacks I always had enough with the `--progress` rsync flags if a download stalled or failed.

so this part needs some logic to make sure a snapshot is fully downloaded: https://github.com/threefoldtech/grid_deployment/blob/development/docker-compose/mainnet/install_grid_bknd.sh#L33-L46

**Comment by A-Harby** [comment]
Could you take a look.

[add retry mechanism and apply it and add a way to show extraction progress](https://github.com/threefoldtech/grid_deployment/pull/92)

**Comment by A-Harby** [comment]
It went well on Testnet; the progress bar was a good progress update, but not sure about the retry because the download and extract were faster than on the mainnet.
 
![image](https://github.com/user-attachments/assets/92019aa1-5833-4dc1-b831-81288b934e3b)

**Comment by coesensbert** [comment]
cool, that looks a lot better indeed. thanks!

**Comment by coesensbert** [comment]
tests look good. did some breaking of an active download and it attempted another retry. The extra output will also make it more clear what is happening

**Comment by coesensbert** [comment]
merged for mainnet, still need to apply it for the other nets

**Comment by A-Harby** [comment]
> merged for mainnet, still need to apply it for the other nets

I created a PR for the testnet, https://github.com/threefoldtech/grid_deployment/pull/96.

I have used the script several times before, so I am sure it works properly.

**Comment by coesensbert** [comment]
> > merged for mainnet, still need to apply it for the other nets
> 
> I created a PR for the testnet, #96.
> 
> I have used the script several times before, so I am sure it works properly.

great, works well here too. Reviewed the PR

**Comment by A-Harby** [comment]
I think this issue can now be closed since both testnet and mainnet scripts are updated with a retry and extraction progress bar, dev and QA download file sizes are comparable small and won't fail like on mainnet, and even testnet didn't fail once.
