### ISSUE TITLE
[tfchain] make sure all nets have tfchain v2.9.2

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_deployment#98]

**Comment by xmonader** [comment]
Which were missing?

**Comment by coesensbert** [comment]
https://github.com/threefoldtech/grid_deployment/commit/cb574d495b7da37a8769cff106a1de3f740213b3
https://github.com/threefoldtech/grid_deployment/commit/64fc4d884584b200b263a129cb30a7c5e645f107
https://github.com/threefoldtech/grid_deployment/commit/ac8494cf50dcf949bfa0811bfc87e6c34a78bc28
https://github.com/threefoldtech/grid_deployment/commit/ea26ba55b48345b9a92173fa62a6bddb70f19d3f

**Comment by coesensbert** [comment]
> Which were missing?

here is the list: https://github.com/threefoldtech/tf_operations/issues/2938#issuecomment-2485577468

**Comment by coesensbert** [comment]
done
